#!/usr/bin/env bash

version=$1

export image_name=$(echo ${version} | sed -re 's#:[^:/]*/#-#g' | sed -re 's/:[^:/]*$//')
export image_version=$(echo ${version} | sed -re 's#/[^:/]*:#-#g' | sed -re 's/^[^:/]*://')
